// Code generated by "stringer -type=ConnectionStatus"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_CONNECTED-0]
	_ = x[CONNECTED-1]
	_ = x[LOST-2]
}

const _ConnectionStatus_name = "NOT_CONNECTEDCONNECTEDLOST"

var _ConnectionStatus_index = [...]uint8{0, 13, 22, 26}

func (i ConnectionStatus) String() string {
	if i < 0 || i >= ConnectionStatus(len(_ConnectionStatus_index)-1) {
		return "ConnectionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionStatus_name[_ConnectionStatus_index[i]:_ConnectionStatus_index[i+1]]
}
